[package]
name = "export-content"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
miette = { version = "7.6.0", features = ["fancy"] }
ratatui = "0.30.0"
regex = "1.11.1"
serde = { version = "1.0", features = ["derive"] }
serde-saphyr = { version = "1", default-features = false, features = [
  "deserialize",
] }
thiserror = "2.0.12"

[lints]
workspace = true
