minty_impl! {
    mint::Vector2<f32> => glam::Vec2,
    mint::Vector3<f32> => glam::Vec3,
    mint::Vector4<f32> => glam::Vec4,
    mint::Vector2<i32> => glam::IVec2,
    mint::Vector3<i32> => glam::IVec3,
    mint::Vector4<i32> => glam::IVec4,
    mint::Vector2<u32> => glam::UVec2,
    mint::Vector3<u32> => glam::UVec3,
    mint::Vector4<u32> => glam::UVec4,
    // bool vectors are disabled due to https://github.com/LPGhatguy/crevice/issues/36
    // mint::Vector2<bool> => glam::BVec2,
    // mint::Vector3<bool> => glam::BVec3,
    // mint::Vector4<bool> => glam::BVec4,
    mint::Vector2<f64> => glam::DVec2,
    mint::Vector3<f64> => glam::DVec3,
    mint::Vector4<f64> => glam::DVec4,
    mint::ColumnMatrix2<f32> => glam::Mat2,
    mint::ColumnMatrix3<f32> => glam::Mat3,
    mint::ColumnMatrix4<f32> => glam::Mat4,
    mint::ColumnMatrix2<f64> => glam::DMat2,
    mint::ColumnMatrix3<f64> => glam::DMat3,
    mint::ColumnMatrix4<f64> => glam::DMat4,
}
