[package]
name = "gpu-preprocessing"
edition = "2024"
publish = false

[dependencies]
bevy = { path = "../..", default-features = false, features = [
  "std",
  "async_executor",
  "multi_threaded",
  "bevy_log",
  "bevy_asset",
  "bevy_pbr",
  "bevy_render",
  "bevy_core_pipeline",
  "bevy_window",
  "bevy_anti_alias",
  "png",
] }
image = { version = "0.25", default-features = false, features = ["png"] }

[profile.dev]
debug = 0
opt-level = 1
