toml-version = "v1.1.0"

[format.rules]
trailing-comment-alignment = true
trailing-comment-space-width = 1

[lint.rules]
tables-out-of-order = "off"

[schema]
enabled = true
strict = false                                           # allow additional properties
catalog = {
  paths = [
    "https://www.schemastore.org/api/json/catalog.json",
  ],
}

[[schemas]]
toml-version = "v1.1.0"
path = "https://www.schemastore.org/cargo.json"
include = ["Cargo.toml"]
format.rules = {
  array-values-order.enabled = false,
  table-keys-order.enabled = false
}

[[schemas]]
toml-version = "v1.0.0"
path = "https://catalog.lintel.tools/schemas/rust/clippy/latest.json"
include = ["clippy.toml"]
format.rules = {
  array-values-order.enabled = false,
  table-keys-order.enabled = false
}
