pub(crate) use bench_check::*;
pub(crate) use cfg_check::*;
pub(crate) use clippy::*;
pub(crate) use compile::*;
pub(crate) use compile_check::*;
pub(crate) use compile_fail::*;
pub(crate) use doc::*;
pub(crate) use doc_check::*;
pub(crate) use doc_test::*;
pub(crate) use example_check::*;
pub(crate) use format::*;
pub(crate) use lints::*;
pub(crate) use test::*;
pub(crate) use test_check::*;

mod bench_check;
mod cfg_check;
mod clippy;
mod compile;
mod compile_check;
mod compile_fail;
mod doc;
mod doc_check;
mod doc_test;
mod example_check;
mod format;
mod lints;
mod test;
mod test_check;
