pub use bench_check::*;
pub use clippy::*;
pub use compile::*;
pub use compile_check::*;
pub use compile_fail::*;
pub use doc::*;
pub use doc_check::*;
pub use doc_test::*;
pub use example_check::*;
pub use format::*;
pub use integration_test::*;
pub use integration_test_check::*;
pub use integration_test_clean::*;
pub use lints::*;
pub use test::*;
pub use test_check::*;

mod bench_check;
mod clippy;
mod compile;
mod compile_check;
mod compile_fail;
mod doc;
mod doc_check;
mod doc_test;
mod example_check;
mod format;
mod integration_test;
mod integration_test_check;
mod integration_test_clean;
mod lints;
mod test;
mod test_check;
