pub use bench_check::*;
pub use bevy_a11y::*;
pub use bevy_android::*;
pub use bevy_animation::*;
pub use bevy_anti_alias::*;
pub use bevy_app::*;
pub use bevy_ecs::*;
pub use clippy::*;
pub use clippy_android::*;
pub use clippy_dlss::*;
pub use clippys::*;
pub use compile::*;
pub use compile_check::*;
pub use compile_fail::*;
pub use doc::*;
pub use doc_check::*;
pub use doc_test::*;
pub use example_check::*;
pub use format::*;
pub use integration_test::*;
pub use integration_test_check::*;
pub use integration_test_clean::*;
pub use lints::*;
pub use test::*;
pub use test_check::*;

mod bench_check;
mod bevy_a11y;
mod bevy_android;
mod bevy_animation;
mod bevy_anti_alias;
mod bevy_app;
mod bevy_ecs;
mod clippy;
mod clippy_android;
mod clippy_dlss;
mod clippy_permutations;
mod clippys;
mod compile;
mod compile_check;
mod compile_fail;
mod doc;
mod doc_check;
mod doc_test;
mod example_check;
mod format;
mod integration_test;
mod integration_test_check;
mod integration_test_clean;
mod lints;
mod test;
mod test_check;
