[package]
name = "bevy_ui_dock"
version = "0.20.0-dev"
edition = "2024"
description = "Dock layout data model for Bevy UI"
homepage = "https://bevy.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

[dependencies]
# bevy
bevy_ecs = { path = "../bevy_ecs", version = "0.20.0-dev" }
bevy_reflect = { path = "../bevy_reflect", version = "0.20.0-dev" }
bevy_ui_widgets = { path = "../bevy_ui_widgets", version = "0.20.0-dev" }

# other
serde = { version = "1", features = ["derive"], optional = true }
thiserror = { version = "2", default-features = false }

[dev-dependencies]
ron = "0.12"

[features]
default = []
serialize = ["dep:serde", "bevy_ui_widgets/serialize"]

[lints]
workspace = true

[package.metadata.docs.rs]
rustdoc-args = [
  "-Zunstable-options",
  "--generate-link-to-definition",
  "--generate-macro-expansion",
]
all-features = true
