[package]
name = "simple-ecs-test"
edition = "2024"

# We depend on bevy in both normal and dev dependencies to verify that the proc macros still work.

[dependencies]
bevy = { path = "../../" }

[dev-dependencies]
bevy = { path = "../../" }

[patch.crates-io]
wesl = { git = "https://github.com/webgpu-tools/wesl-rs", rev = "2e24e41d80f5f453dad2c70b5471160ff42f396e" }
