use palette::{Hsl, Hsv, Hwb, IntoColor, Lab, Lch, LinSrgb, Oklab, Oklch, Srgb, Xyz};

const TEST_COLORS: &[(f32, f32, f32, &str)] = &[
    (0., 0., 0., "black"),
    (0., 0., 0.0000002, "black_plus_epsilon"),
    (1., 1., 0.9999998, "white_minus_epsilon"),
    (1., 1., 1., "white"),
    (1., 0., 0., "red"),
    (0., 1., 0., "green"),
    (0., 0., 1., "blue"),
    (1., 1., 0., "yellow"),
    (1., 0., 1., "magenta"),
    (0., 1., 1., "cyan"),
    (0.5, 0.5, 0.5, "gray"),
    (0.5, 0.5, 0., "olive"),
    (0.5, 0., 0.5, "purple"),
    (0., 0.5, 0.5, "teal"),
    (0.5, 0., 0., "maroon"),
    (0., 0.5, 0., "lime"),
    (0., 0., 0.5, "navy"),
    (0.5, 0.5, 0., "orange"),
    (0.5, 0., 0.5, "fuchsia"),
    (0., 0.5, 0.5, "aqua"),
];

/// Pre-computed okhsl results of [`TEST_COLORS`].
/// See <https://github.com/bevyengine/bevy/pull/24137> for how this was computed.
#[expect(
    clippy::excessive_precision,
    reason = "The results are copied from output of script"
)]
const TEST_COLORS_OKHSL: &[[f32; 3]] = &[
    [0., 0., 0.],
    [
        264.05202063805507,
        0.9999976852561692,
        0.00019314567939689165,
    ],
    [0., 0., 0.9999999923961898],
    [0., 0., 0.9999999758763981],
    [29.23388519234263, 1.0000000052082665, 0.5680846525040862],
    [142.49533888780996, 0.999999970072876, 0.8445289645307816],
    [264.052020638055, 0.9999999966883574, 0.3665653394260194],
    [109.76923207652122, 1.0000000336324515, 0.9627043968088945],
    [328.36341792345144, 0.9999999982842802, 0.6532987448472438],
    [194.76894793196382, 0.9999999858415309, 0.889848301619521],
    [0., 0., 0.5337598228073358],
    [109.76923207652133, 1.0000004293546714, 0.5117162225399476],
    [328.36341792345144, 0.9999999247891016, 0.33011042396630463],
    [194.7689479319638, 0.9999998087565706, 0.4687233442820504],
    [29.23388519234263, 1.0000000079893017, 0.28080442778247217],
    [142.49533888780996, 0.9999999780939269, 0.4420348389571636],
    [264.052020638055, 0.9999999965721178, 0.1673431798736403],
    [109.76923207652133, 1.0000004293546714, 0.5117162225399476],
    [328.36341792345144, 0.9999999247891016, 0.33011042396630463],
    [194.7689479319638, 0.9999998087565706, 0.4687233442820504],
];

/// Pre-computed okhsv results of [`TEST_COLORS`].
/// See <https://github.com/bevyengine/bevy/pull/24137> for how this was computed.
#[expect(
    clippy::excessive_precision,
    reason = "The results are copied from output of script"
)]
const TEST_COLORS_OKHSV: &[[f32; 3]] = &[
    [0., 0., 0.],
    [
        264.05202063805507,
        0.9999910912349016,
        0.0004986484139424938,
    ],
    [0., 0., 0.9999999923961898],
    [0., 0., 0.9999999758763981],
    [29.23388519234263, 1.0000000118548495, 1.0000000001685643],
    [142.49533888780996, 0.9999998547944557, 0.9999999884428643],
    [264.052020638055, 0.9999999869716024, 0.9999999646150842],
    [109.76923207652122, 1.0000004272507257, 1.0000000319591922],
    [328.36341792345144, 0.9999999851480317, 0.9999999978651299],
    [194.76894793196382, 0.9999997954575895, 0.9999999950078031],
    [0., 0., 0.5337598228073358],
    [109.76923207652133, 1.0000004272507266, 0.5318634934374442],
    [328.36341792345144, 0.9999999851480317, 0.5106204722384122],
    [194.7689479319638, 0.9999997954575874, 0.527824149473251],
    [29.23388519234263, 1.0000000118548495, 0.5022602924281349],
    [142.49533888780996, 0.999999854794456, 0.525059257999103],
    [264.052020638055, 0.9999999869716024, 0.4749665533554043],
    [109.76923207652133, 1.0000004272507266, 0.5318634934374442],
    [328.36341792345144, 0.9999999851480317, 0.5106204722384122],
    [194.7689479319638, 0.9999997954575874, 0.527824149473251],
];

fn main() {
    println!(
        "#![cfg_attr(rustfmt, rustfmt::skip)]
// Generated by gen_tests. Do not edit.
#[cfg(test)]
use crate::{{
    Hsla, Hsva, Hwba, Laba, Lcha, LinearRgba, Okhsla, Okhsva, Oklaba, Oklcha, Srgba, Xyza,
}};

#[cfg(test)]
pub struct TestColor {{
    pub name: &'static str,
    pub rgb: Srgba,
    pub linear_rgb: LinearRgba,
    pub hsl: Hsla,
    pub hsv: Hsva,
    pub hwb: Hwba,
    pub lab: Laba,
    pub lch: Lcha,
    pub oklab: Oklaba,
    pub oklch: Oklcha,
    pub xyz: Xyza,
    pub okhsl: Okhsla,
    pub okhsv: Okhsva,
}}
"
    );

    println!("// Table of equivalent colors in various color spaces");
    println!("#[cfg(test)]");
    println!("pub const TEST_COLORS: &[TestColor] = &[");
    for (i, (r, g, b, name)) in TEST_COLORS.iter().enumerate() {
        let srgb = Srgb::new(*r, *g, *b);
        let linear_rgb: LinSrgb = srgb.into_color();
        let hsl: Hsl = srgb.into_color();
        let hsv: Hsv = srgb.into_color();
        let hwb: Hwb = srgb.into_color();
        let lab: Lab = srgb.into_color();
        let lch: Lch = srgb.into_color();
        let oklab: Oklab = srgb.into_color();
        let oklch: Oklch = srgb.into_color();
        let xyz: Xyz = srgb.into_color();
        let okhsl = TEST_COLORS_OKHSL[i];
        let okhsv = TEST_COLORS_OKHSV[i];
        println!("    // {name}");
        println!(
            "    TestColor {{
        name: \"{name}\",
        rgb: Srgba::new({}, {}, {}, 1.0),
        linear_rgb: LinearRgba::new({}, {}, {}, 1.0),
        hsl: Hsla::new({}, {}, {}, 1.0),
        hsv: Hsva::new({}, {}, {}, 1.0),
        hwb: Hwba::new({}, {}, {}, 1.0),
        lab: Laba::new({}, {}, {}, 1.0),
        lch: Lcha::new({}, {}, {}, 1.0),
        oklab: Oklaba::new({}, {}, {}, 1.0),
        oklch: Oklcha::new({}, {}, {}, 1.0),
        xyz: Xyza::new({}, {}, {}, 1.0),
        okhsl: Okhsla::new({}, {}, {}, 1.0),
        okhsv: Okhsva::new({}, {}, {}, 1.0),
    }},",
            VariablePrecision(srgb.red),
            VariablePrecision(srgb.green),
            VariablePrecision(srgb.blue),
            VariablePrecision(linear_rgb.red),
            VariablePrecision(linear_rgb.green),
            VariablePrecision(linear_rgb.blue),
            VariablePrecision(hsl.hue.into_positive_degrees()),
            VariablePrecision(hsl.saturation),
            VariablePrecision(hsl.lightness),
            VariablePrecision(hsv.hue.into_positive_degrees()),
            VariablePrecision(hsv.saturation),
            VariablePrecision(hsv.value),
            VariablePrecision(hwb.hue.into_positive_degrees()),
            VariablePrecision(hwb.whiteness),
            VariablePrecision(hwb.blackness),
            VariablePrecision(lab.l / 100.0),
            VariablePrecision(lab.a / 100.0),
            VariablePrecision(lab.b / 100.0),
            VariablePrecision(lch.l / 100.0),
            VariablePrecision(lch.chroma / 100.0),
            VariablePrecision(lch.hue.into_positive_degrees()),
            VariablePrecision(oklab.l),
            VariablePrecision(oklab.a),
            VariablePrecision(oklab.b),
            VariablePrecision(oklch.l),
            VariablePrecision(oklch.chroma),
            VariablePrecision(oklch.hue.into_positive_degrees()),
            VariablePrecision(xyz.x),
            VariablePrecision(xyz.y),
            VariablePrecision(xyz.z),
            VariablePrecision(okhsl[0]),
            VariablePrecision(okhsl[1]),
            VariablePrecision(okhsl[2]),
            VariablePrecision(okhsv[0]),
            VariablePrecision(okhsv[1]),
            VariablePrecision(okhsv[2]),
        );
    }
    println!("];");
}

struct VariablePrecision(f32);

impl core::fmt::Display for VariablePrecision {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        if self.0.fract() == 0.0 {
            return write!(f, "{}.0", self.0);
        }
        write!(f, "{}", self.0)
    }
}
