use palette::{Hsl, Hsv, Hwb, IntoColor, Lab, Lch, LinSrgb, Oklab, Oklch, Srgb, Xyz};

const TEST_COLORS: &[(f32, f32, f32, &str)] = &[
    (0., 0., 0., "black"),
    (1., 1., 1., "white"),
    (1., 0., 0., "red"),
    (0., 1., 0., "green"),
    (0., 0., 1., "blue"),
    (1., 1., 0., "yellow"),
    (1., 0., 1., "magenta"),
    (0., 1., 1., "cyan"),
    (0.5, 0.5, 0.5, "gray"),
    (0.5, 0.5, 0., "olive"),
    (0.5, 0., 0.5, "purple"),
    (0., 0.5, 0.5, "teal"),
    (0.5, 0., 0., "maroon"),
    (0., 0.5, 0., "lime"),
    (0., 0., 0.5, "navy"),
    (0.5, 0.5, 0., "orange"),
    (0.5, 0., 0.5, "fuchsia"),
    (0., 0.5, 0.5, "aqua"),
];
/// Pre-computed okhsl results of [`TEST_COLORS`].
const TEST_COLORS_OKHSL: &[[f32; 3]] = &[
    [0., 0., 0.], // The result of original javascript implemention is [0, NaN, 0].
    [89.87556309590242, 0.5582831888483675, 0.9999999923961898],
    [29.23388519234263, 1.0000000001433997, 0.5680846525040862],
    [142.49533888780996, 0.9999999700728788, 0.8445289645307816],
    [264.052020638055, 0.9999999948631134, 0.3665653394260194],
    [109.76923207652122, 1.0000000336324515, 0.9627043968088945],
    [328.36341792345144, 1.000039018792486, 0.6532987448472438],
    [194.76894793196382, 0.9999999858415329, 0.889848301619521],
    [89.87556282857139, 1.1616558204531687e-7, 0.5337598228073358],
    [109.76923207652133, 1.0000004489650085, 0.5117162225399476],
    [328.36341792345144, 1.0006210729018223, 0.33011042396630463],
    [194.7689479319638, 0.9999994637526137, 0.4687233442820504],
    [29.23388519234263, 0.9996788048327606, 0.28080442778247217],
    [142.49533888780996, 0.9999999579156374, 0.4420348389571636],
    [264.052020638055, 0.9999976560886634, 0.1673431798736403],
    [109.76923207652133, 1.0000004489650085, 0.5117162225399476],
    [328.36341792345144, 1.0006210729018223, 0.33011042396630463],
    [194.7689479319638, 0.9999994637526137, 0.4687233442820504],
];
/// Pre-computed okhsv results of [`TEST_COLORS`].
const TEST_COLORS_OKHSV: &[[f32; 3]] = &[
    [0., 0., 0.], // The result of original javascript implemention is [0, NaN, NaN].
    [89.87556309590242, 1.0347523928230576e-7, 1.000000027003774],
    [29.23388519234263, 0.9995219692256989, 1.0000000001685625],
    [142.49533888780996, 0.9999997210415695, 0.9999999884428648],
    [264.052020638055, 0.9999910912349018, 0.9999999646150918],
    [109.76923207652122, 1.0000004467649033, 1.0000000319591924],
    [328.36341792345144, 1.000122136833694, 0.9999999978651268],
    [194.76894793196382, 0.9999994264606504, 0.9999999950078027],
    [89.87556282857139, 1.0347523926099617e-7, 0.5337598416065157],
    [109.76923207652133, 1.0000004467649042, 0.5318634934435551],
    [328.36341792345144, 1.0001221368336943, 0.5106197804980503],
    [194.7689479319638, 0.999999426460651, 0.5278241496179404],
    [29.23388519234263, 0.9995219692256992, 0.5022645128400224],
    [142.49533888780996, 0.9999997210415695, 0.5250592582180916],
    [264.052020638055, 0.9999910912349016, 0.47496664028144414],
    [109.76923207652133, 1.0000004467649042, 0.5318634934435551],
    [328.36341792345144, 1.0001221368336943, 0.5106197804980503],
    [194.7689479319638, 0.999999426460651, 0.5278241496179404],
];

fn main() {
    println!(
        "// Generated by gen_tests. Do not edit.
#[cfg(test)]
use crate::{{
    okhsla::Okhsla, Hsla, Hsva, Hwba, Laba, Lcha, LinearRgba, Okhsva, Oklaba, Oklcha, Srgba, Xyza,
}};

#[cfg(test)]
pub struct TestColor {{
    pub name: &'static str,
    pub rgb: Srgba,
    pub linear_rgb: LinearRgba,
    pub hsl: Hsla,
    pub hsv: Hsva,
    pub hwb: Hwba,
    pub lab: Laba,
    pub lch: Lcha,
    pub oklab: Oklaba,
    pub oklch: Oklcha,
    pub xyz: Xyza,
    pub okhsl: Okhsla,
    pub okhsv: Okhsva,
}}
"
    );

    println!("// Table of equivalent colors in various color spaces");
    println!("#[cfg(test)]");
    println!("pub const TEST_COLORS: &[TestColor] = &[");
    for (i, (r, g, b, name)) in TEST_COLORS.iter().enumerate() {
        let srgb = Srgb::new(*r, *g, *b);
        let linear_rgb: LinSrgb = srgb.into_color();
        let hsl: Hsl = srgb.into_color();
        let hsv: Hsv = srgb.into_color();
        let hwb: Hwb = srgb.into_color();
        let lab: Lab = srgb.into_color();
        let lch: Lch = srgb.into_color();
        let oklab: Oklab = srgb.into_color();
        let oklch: Oklch = srgb.into_color();
        let xyz: Xyz = srgb.into_color();
        let okhsl = TEST_COLORS_OKHSL[i];
        let okhsv = TEST_COLORS_OKHSV[i];
        println!("    // {name}");
        println!(
            "    TestColor {{
        name: \"{name}\",
        rgb: Srgba::new({}, {}, {}, 1.0),
        linear_rgb: LinearRgba::new({}, {}, {}, 1.0),
        hsl: Hsla::new({}, {}, {}, 1.0),
        hsv: Hsva::new({}, {}, {}, 1.0),
        hwb: Hwba::new({}, {}, {}, 1.0),
        lab: Laba::new({}, {}, {}, 1.0),
        lch: Lcha::new({}, {}, {}, 1.0),
        oklab: Oklaba::new({}, {}, {}, 1.0),
        oklch: Oklcha::new({}, {}, {}, 1.0),
        xyz: Xyza::new({}, {}, {}, 1.0),
        okhsl: Okhsla::new({}, {}, {}, 1.0),
        okhsv: Okhsva::new({}, {}, {}, 1.0),
    }},",
            VariablePrecision(srgb.red),
            VariablePrecision(srgb.green),
            VariablePrecision(srgb.blue),
            VariablePrecision(linear_rgb.red),
            VariablePrecision(linear_rgb.green),
            VariablePrecision(linear_rgb.blue),
            VariablePrecision(hsl.hue.into_positive_degrees()),
            VariablePrecision(hsl.saturation),
            VariablePrecision(hsl.lightness),
            VariablePrecision(hsv.hue.into_positive_degrees()),
            VariablePrecision(hsv.saturation),
            VariablePrecision(hsv.value),
            VariablePrecision(hwb.hue.into_positive_degrees()),
            VariablePrecision(hwb.whiteness),
            VariablePrecision(hwb.blackness),
            VariablePrecision(lab.l / 100.0),
            VariablePrecision(lab.a / 100.0),
            VariablePrecision(lab.b / 100.0),
            VariablePrecision(lch.l / 100.0),
            VariablePrecision(lch.chroma / 100.0),
            VariablePrecision(lch.hue.into_positive_degrees()),
            VariablePrecision(oklab.l),
            VariablePrecision(oklab.a),
            VariablePrecision(oklab.b),
            VariablePrecision(oklch.l),
            VariablePrecision(oklch.chroma),
            VariablePrecision(oklch.hue.into_positive_degrees()),
            VariablePrecision(xyz.x),
            VariablePrecision(xyz.y),
            VariablePrecision(xyz.z),
            VariablePrecision(okhsl[0]),
            VariablePrecision(okhsl[1]),
            VariablePrecision(okhsl[2]),
            VariablePrecision(okhsv[0]),
            VariablePrecision(okhsv[1]),
            VariablePrecision(okhsv[2]),
        );
    }
    println!("];");
}

struct VariablePrecision(f32);

impl core::fmt::Display for VariablePrecision {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        if self.0.fract() == 0.0 {
            return write!(f, "{}.0", self.0);
        }
        write!(f, "{}", self.0)
    }
}
