[package]
name = "benches"
edition = "2024"
description = "Benchmarks that test Bevy's performance"
publish = false
license = "MIT OR Apache-2.0"
# Do not automatically discover benchmarks, we specify them manually instead.
autobenches = false

[dependencies]
# The primary crate that runs and analyzes our benchmarks. This is a regular dependency because the
# `bench!` macro refers to it in its documentation.
criterion = { version = "0.8.0", features = ["html_reports"] }
seq-macro = "0.3.6"

# Bevy crates
bevy_app = { path = "../crates/bevy_app", optional = true }
bevy_ecs = { path = "../crates/bevy_ecs", optional = true, features = [
  "multi_threaded",
] }
bevy_extract = { path = "../crates/bevy_extract", optional = true }
bevy_math = { path = "../crates/bevy_math", optional = true }
bevy_picking = { path = "../crates/bevy_picking", optional = true, features = [
  "mesh_picking",
] }
bevy_reflect = { path = "../crates/bevy_reflect", optional = true, features = [
  "functions",
] }
bevy_camera = { path = "../crates/bevy_camera", optional = true }
bevy_mesh = { path = "../crates/bevy_mesh", optional = true }
bevy_asset = { path = "../crates/bevy_asset", optional = true }
bevy_render = { path = "../crates/bevy_render", optional = true }
bevy_scene = { path = "../crates/bevy_scene", optional = true }
bevy_tasks = { path = "../crates/bevy_tasks", optional = true }
bevy_transform = { path = "../crates/bevy_transform", optional = true }
bevy_ui = { path = "../crates/bevy_ui", optional = true }
bevy_ui_widgets = { path = "../crates/bevy_ui_widgets", optional = true }
bevy_platform = { path = "../crates/bevy_platform", optional = true, default-features = false, features = [
  "std",
  "bytemuck",
] }

# Other crates
glam = { version = "0.33.2", default-features = false, features = [
  "std",
  "all-types",
  "rand",
  "bytemuck",
] }
rand = "0.10"
chacha20 = { version = "0.10.0", default-features = false, features = ["rng"] }
nonmax = { version = "0.5", default-features = false }
bytemuck = { version = "1", default-features = false, features = [
  "derive",
  "must_cast",
] }

[features]
default = [
  "bench_camera",
  "bench_ecs",
  "bench_math",
  "bench_picking",
  "bench_platform",
  "bench_reflect",
  "bench_render",
  "bench_scene",
  "bench_tasks",
  "bench_transform",
]

bench_camera = ["dep:bevy_camera", "dep:bevy_math"]

bench_ecs = [
  "dep:bevy_ecs",
  "dep:bevy_app",
  "dep:bevy_math",
  "dep:bevy_reflect",
  "dep:bevy_tasks",
  "bevy_math/bevy_reflect",
]

bench_math = ["dep:bevy_math"]

bench_picking = ["dep:bevy_picking", "dep:bevy_math"]

bench_platform = [
  "dep:bevy_platform",
  "dep:bevy_math",
  "bytemuck/min_const_generics",
]

bench_reflect = ["dep:bevy_reflect", "dep:bevy_platform"]

bench_render = [
  "dep:bevy_render",
  "dep:bevy_app",
  "dep:bevy_asset",
  "dep:bevy_camera",
  "dep:bevy_ecs",
  "dep:bevy_extract",
  "dep:bevy_mesh",
  "dep:bevy_reflect",
]

bench_scene = [
  "dep:bevy_scene",
  "dep:bevy_app",
  "dep:bevy_asset",
  "dep:bevy_ecs",
  "dep:bevy_ui",
  "dep:bevy_ui_widgets",
  "dep:bevy_reflect",
]

bench_tasks = ["dep:bevy_tasks"]

bench_transform = [
  "dep:bevy_transform",
  "dep:bevy_ecs",
  "dep:bevy_math",
  "dep:bevy_tasks",
]

[lints.clippy]
doc_markdown = "warn"
manual_let_else = "warn"
match_same_arms = "warn"
redundant_closure_for_method_calls = "warn"
redundant_else = "warn"
semicolon_if_nothing_returned = "warn"
type_complexity = "allow"
undocumented_unsafe_blocks = "warn"
unwrap_or_default = "warn"
needless_lifetimes = "allow"
too_many_arguments = "allow"
nonstandard_macro_braces = "warn"

ptr_as_ptr = "warn"
ptr_cast_constness = "warn"
ref_as_ptr = "warn"

# see: https://github.com/bevyengine/bevy/pull/15375#issuecomment-2366966219
too_long_first_doc_paragraph = "allow"

allow_attributes = "warn"
allow_attributes_without_reason = "warn"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(docsrs_dep)'] }
unsafe_op_in_unsafe_fn = "warn"
unused_qualifications = "warn"

[lib]
# This fixes the "Unrecognized Option" error when running commands like
# `cargo bench -- --save-baseline before` by disabling the default benchmark harness.
# See <https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options>
# for more information.
bench = false

[[bench]]
name = "ecs"
path = "benches/bevy_ecs/main.rs"
harness = false
required-features = ["bench_ecs"]

[[bench]]
name = "math"
path = "benches/bevy_math/main.rs"
harness = false
required-features = ["bench_math"]

[[bench]]
name = "picking"
path = "benches/bevy_picking/main.rs"
harness = false
required-features = ["bench_picking"]

[[bench]]
name = "reflect"
path = "benches/bevy_reflect/main.rs"
harness = false
required-features = ["bench_reflect"]

[[bench]]
name = "render"
path = "benches/bevy_render/main.rs"
harness = false
required-features = ["bench_render"]

[[bench]]
name = "scene"
path = "benches/bevy_scene/main.rs"
harness = false
required-features = ["bench_scene"]

[[bench]]
name = "tasks"
path = "benches/bevy_tasks/main.rs"
harness = false
required-features = ["bench_tasks"]

[[bench]]
name = "camera"
path = "benches/bevy_camera/main.rs"
harness = false
required-features = ["bench_camera"]

[[bench]]
name = "transform"
path = "benches/bevy_transform/main.rs"
harness = false
required-features = ["bench_transform"]

[[bench]]
name = "platform"
path = "benches/bevy_platform/main.rs"
harness = false
required-features = ["bench_platform"]
