[package]
name = "zero_day"
version = "0.1.0"
edition = "2024"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
bevy = { path = "../../..", features = [
  "bevy_camera_controller",
  "free_camera",
  "bevy_solari",
] }

argh = "0.1.12"

[features]
# Use `--features dlss` to enable denoising with DLSS RR in Solari. It is off by default,
# because a build with it needs the DLSS SDK.
dlss = ["bevy/dlss"]
force_disable_dlss = ["bevy/force_disable_dlss"]
