name: Update labels

on:
  schedule:
    - cron: '5 4 * * *'

jobs:
  run-script:
    permissions:
      pull-requests: "write"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      # This job checks each open PR if the S-Merge-Conflicts label is correct.
      # Allows for reviewers to search for ready PRs with:
      #   `is:pr is:open -label:S-Merge-Conflicts -author:@me label:S-Needs-Review -reviewed-by:@me`
      # Script runs twice if any PRs have mergeable=UNKNOWN to allow for calculation
      - name: Update merge conflict labels
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./.github/tools/label-merge-conflicts.sh
          RET1=$?
          if [[ "$RET1" -gt 0 ]]; then
            sleep 60
            ./.github/tools/label-merge-conflicts.sh
            RET2=$?
            exit $RET2
          fi
